name: pharmatrack

services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: pharmatrack
      POSTGRES_PASSWORD: pharmatrack
      POSTGRES_DB: pharmatrack
    ports:
      - '5432:5432'
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U pharmatrack -d pharmatrack']
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command:
      [
        'redis-server',
        '--appendonly',
        'yes',
        '--maxmemory',
        '128mb',
        '--maxmemory-policy',
        'allkeys-lru',
      ]
    ports:
      - '6379:6379'
    volumes:
      - ./.data/redis:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 10

  localstack:
    image: localstack/localstack:3
    restart: unless-stopped
    environment:
      SERVICES: s3
      DEFAULT_REGION: ap-southeast-1
      # Automatically create the pharmatrack-uploads bucket on startup
      AWS_DEFAULT_REGION: ap-southeast-1
    ports:
      - '4566:4566'
    volumes:
      - ./.data/localstack:/var/lib/localstack
      - ./localstack-init:/etc/localstack/init/ready.d
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:4566/_localstack/health']
      interval: 5s
      timeout: 5s
      retries: 10
